# 服务端口
server:
  port: 9020

spring:
  #mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/zmail?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  notEmpty: true


# 日志配置
logging:
  level:
    root: info

#dubbo配置
dubbo:
  application:
    name: manage-service
  protocol:
    name: dubbo
  #zk配置
  registry:
    address: 10.0.6.99:2181
    protocol: zookeeper
  scan:
    base-packages: com.zclorne.zmall
